# Generated by Django 5.2.14 on 2026-05-14 00:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('boleta', 'Boleta')], default='factura', max_length=10)),
                ('serie', models.CharField(default='F001', max_length=4)),
                ('correlativo', models.PositiveIntegerField()),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('pagada', 'Pagada'), ('parcial', 'Pago parcial'), ('anulada', 'Anulada')], default='emitida', max_length=10)),
                ('estado_sunat', models.CharField(choices=[('pendiente', 'Pendiente envío'), ('aceptada', 'Aceptada por SUNAT'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada (CDR)')], default='pendiente', max_length=12)),
                ('hash_sunat', models.CharField(blank=True, help_text='Hash simulado para demo.', max_length=80)),
                ('observaciones', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Factura / Boleta',
                'verbose_name_plural': 'Facturas y Boletas',
                'ordering': ['-fecha_emision', '-correlativo'],
                'unique_together': {('serie', 'correlativo')},
            },
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('unidad', models.CharField(default='UND', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='facturacion.factura')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_factura', to='catalogo.producto')),
            ],
            options={
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('deposito', 'Depósito en cuenta'), ('yape', 'Yape / Plin'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('credito', 'Letra / Crédito')], default='transferencia', max_length=15)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-creado'],
            },
        ),
    ]
