# Generated by Django 5.2.14 on 2026-05-14 00:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('validez_dias', models.PositiveIntegerField(default=15)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('incluye_igv', models.BooleanField(default=True, help_text='Si TRUE, los precios mostrados YA incluyen IGV.')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('condiciones', models.TextField(blank=True, default='1. Precios expresados en Soles peruanos (PEN) e incluyen IGV.\n2. Forma de pago: contado o crédito 15 días sujeto a evaluación.\n3. Tiempo de entrega: 2 a 5 días hábiles tras confirmación.\n4. La cotización pierde validez al vencimiento indicado.')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada al cliente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='borrador', max_length=20)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('respondida_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='clientes.cliente')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='LineaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('unidad', models.CharField(default='UND', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='cotizaciones.cotizacion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_cotizacion', to='catalogo.producto')),
            ],
            options={
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('tipo_cliente', models.CharField(choices=[('persona', 'Persona natural'), ('empresa', 'Empresa')], default='empresa', max_length=10)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('ruc', models.CharField(blank=True, max_length=11)),
                ('nombre_contacto', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('departamento', models.CharField(blank=True, max_length=80)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('cotizada', 'Cotización emitida'), ('cerrada', 'Cerrada'), ('descartada', 'Descartada')], default='pendiente', max_length=20)),
                ('nota_interna', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Solicitud de cotización',
                'verbose_name_plural': 'Solicitudes de cotización',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_snapshot', models.CharField(max_length=200)),
                ('sku_snapshot', models.CharField(max_length=60)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_solicitud', to='catalogo.producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.solicitudcotizacion')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='cotizaciones.solicitudcotizacion'),
        ),
    ]
