# Generated by Django 5.2.14 on 2026-05-14 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('tipo_cliente', models.CharField(choices=[('persona', 'Persona natural'), ('empresa', 'Empresa')], default='empresa', max_length=10)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('ruc', models.CharField(blank=True, max_length=11)),
                ('nombre_contacto', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('departamento', models.CharField(blank=True, max_length=80)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('enviada', 'Cotización enviada'), ('cerrada', 'Cerrada'), ('descartada', 'Descartada')], default='pendiente', max_length=20)),
                ('nota_interna', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de cotización',
                'verbose_name_plural': 'Solicitudes de cotización',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_snapshot', models.CharField(max_length=200)),
                ('sku_snapshot', models.CharField(max_length=60)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_cotizacion', to='catalogo.producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.solicitudcotizacion')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
