# Generated by Django 5.2.14 on 2026-05-14 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('persona', 'Persona natural')], default='empresa', max_length=10)),
                ('razon_social', models.CharField(help_text='Razón social o nombre completo de la persona.', max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('documento', models.CharField(blank=True, help_text='RUC (11 dig) o DNI (8 dig).', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('departamento', models.CharField(blank=True, max_length=80)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('notas', models.TextField(blank=True, help_text='Uso interno.')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['documento'], name='clientes_cl_documen_76f212_idx'), models.Index(fields=['email'], name='clientes_cl_email_eae461_idx')],
            },
        ),
    ]
