# Generated by Django 5.2.14 on 2026-05-14 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre de icono Heroicons (ej: sparkles, beaker, sun)', max_length=80)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas/')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('presentacion', models.CharField(blank=True, help_text='Ej: Galón 4L, Bolsa 25kg, Caja 12u', max_length=120)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('disponibilidad', models.CharField(choices=[('en_stock', 'En stock'), ('bajo_pedido', 'Bajo pedido'), ('agotado', 'Agotado')], default='en_stock', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.marca')),
            ],
            options={
                'ordering': ['-destacado', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'destacado'], name='catalogo_pr_activo_c84eea_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='catalogo_pr_categor_cdb42d_idx'),
        ),
    ]
