# Generated by Django 5.2.14 on 2026-05-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_volumen',
            field=models.CharField(blank=True, help_text="Ej: 'Desde 10 unid: 5% · Desde 50: 10% · Desde 100: 15%'", max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_referencia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio referencial CON IGV. Se auto-llena al cotizar (se puede ajustar).', max_digits=10),
        ),
    ]
