# Generated by Django 5.2.14 on 2026-05-15 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador interno (no se muestra al público).', max_length=60, unique=True)),
                ('titulo', models.CharField(help_text="Nombre amigable para el admin (ej. 'Página de inicio').", max_length=120)),
                ('descripcion', models.CharField(blank=True, help_text='Pequeña ayuda para el editor.', max_length=240)),
                ('icono', models.CharField(blank=True, default='article', help_text='Material icon name (Unfold).', max_length=40)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas del sitio',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(help_text='Identificador interno usado por la web. NO editar.', max_length=80, unique=True)),
                ('etiqueta', models.CharField(help_text="Nombre amigable mostrado al editor (ej. 'Título principal del hero').", max_length=160)),
                ('ayuda', models.CharField(blank=True, help_text='Pista contextual que aparece bajo el campo en el admin.', max_length=300)),
                ('tipo', models.CharField(choices=[('texto', 'Texto corto'), ('textarea', 'Texto largo (párrafo)'), ('html', 'HTML enriquecido'), ('imagen', 'Imagen'), ('numero', 'Número'), ('url', 'Enlace (URL)')], default='texto', max_length=10)),
                ('valor_texto', models.CharField(blank=True, max_length=500)),
                ('valor_textarea', models.TextField(blank=True)),
                ('valor_html', models.TextField(blank=True, help_text="Permite HTML: usa <strong>, <em>, <br> y enlaces &lt;a href='...'&gt;.")),
                ('valor_imagen', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('valor_numero', models.CharField(blank=True, help_text="Acepta texto: '+160', '24h', '100%', etc.", max_length=20)),
                ('valor_url', models.URLField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('pagina', models.ForeignKey(help_text='Sección del sitio a la que pertenece este bloque.', on_delete=django.db.models.deletion.PROTECT, related_name='bloques', to='cms.pagina')),
            ],
            options={
                'verbose_name': 'Bloque de contenido',
                'verbose_name_plural': 'Bloques de contenido',
                'ordering': ['pagina__orden', 'pagina__titulo', 'orden', 'etiqueta'],
            },
        ),
    ]
